version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: psychoAI_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "1488:5431"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d psychoAI_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: