version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: psychoAI_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "1488:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d psychoAI_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  bot:
    build: .
    container_name: psychoAI_bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: "7560654495:AAGnMBWuFX35VVCGWiwrCKngDnNVBYwVlIY"
      DATABASE_URL: "postgresql+asyncpg://admin:admin@db:5432/psychoAI_db"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/source  # Монтируем код бота

volumes:
  pg_data: