"""ref

Revision ID: 128c1008f804
Revises: 7506785d6350
Create Date: 2025-09-26 15:16:21.954701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '128c1008f804'
down_revision = '7506785d6350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_characteristic',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('current_mood', sa.String(length=50), nullable=False, comment='эмоциональное состояние на момент записи'),
    sa.Column('mood_trend', sa.String(length=50), nullable=False, comment='динамика настроения (если есть прошлые записи)'),
    sa.Column('mood_stability', sa.String(length=50), nullable=False, comment='эмоциональная стабильность'),
    sa.Column('risk_group', sa.String(length=50), nullable=False, comment='группа риска'),
    sa.Column('stress_level', sa.String(length=50), nullable=False, comment='уровень стресса'),
    sa.Column('anxiety_level', sa.String(length=50), nullable=False, comment='уровень тревожности'),
    sa.Column('strengths', postgresql.ARRAY(sa.String(length=200)), nullable=False, comment='положительные трейты'),
    sa.Column('weaknesses', postgresql.ARRAY(sa.String(length=200)), nullable=False, comment='негативные трейты'),
    sa.Column('communication_style', sa.String(length=150), nullable=False, comment='стиль коммуникации'),
    sa.Column('personal_insights', postgresql.ARRAY(sa.String(length=200)), nullable=False, comment='психологические инсайты и склонности'),
    sa.Column('recommendations', postgresql.ARRAY(sa.String(length=200)), nullable=False, comment='рекомендации массив'),
    sa.Column('characteristic_accuracy', sa.String(length=10), nullable=False, comment='насколько точная была оценка ИИ в процентах'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dialogs_logging',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('message', sa.String(), nullable=False, comment='Сообщение юзера'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mood',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('mood', sa.Integer(), nullable=False, comment='Настроение юзера от 0 до 10'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_dialogs_logging')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_dialogs_logging',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя из таблицы users'),
    sa.Column('dialogue_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID сессии диалога'),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Роль отправителя (user или assistant)'),
    sa.Column('message_text', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Текст сообщения'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_dialogs_logging_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_dialogs_logging_pkey'))
    )
    op.drop_table('user_mood')
    op.drop_table('user_dialogs_logging')
    op.drop_table('user_characteristic')
    # ### end Alembic commands ###
