"""ref

Revision ID: 2beccdcf9783
Revises: 04410122be77
Create Date: 2025-10-29 05:05:45.960527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2beccdcf9783'
down_revision = '04410122be77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('message', sa.String(), nullable=False, comment='Текст сообщения'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_dialogs_logging')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dialogs_logging',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Сообщение юзера'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_dialogs_logging_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_dialogs_logging_pkey'))
    )
    op.drop_table('user_logs')
    # ### end Alembic commands ###