"""change dialog model

Revision ID: 3505c6759707
Revises: ad64090b7670
Create Date: 2025-09-08 23:43:09.848903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3505c6759707'
down_revision = 'ad64090b7670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dialogs_logging', sa.Column('dialogue_id', sa.UUID(), nullable=False, comment='ID сессии диалога'))
    op.add_column('users_dialogs_logging', sa.Column('role', sa.String(), nullable=False, comment='Роль отправителя (user или assistant)'))
    op.add_column('users_dialogs_logging', sa.Column('message_text', sa.String(), nullable=False, comment='Текст сообщения'))
    op.drop_column('users_dialogs_logging', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dialogs_logging', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Массив сообщений пользователя'))
    op.drop_column('users_dialogs_logging', 'message_text')
    op.drop_column('users_dialogs_logging', 'role')
    op.drop_column('users_dialogs_logging', 'dialogue_id')
    # ### end Alembic commands ###
