"""fix user log field

Revision ID: 5c73eba989bd
Revises: be256bf69a43
Create Date: 2025-10-29 15:04:56.503949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c73eba989bd'
down_revision = 'be256bf69a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logs', sa.Column('message_text', sa.String(), nullable=False, comment='Текст сообщения'))
    op.drop_column('user_logs', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logs', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Текст сообщения'))
    op.drop_column('user_logs', 'message_text')
    # ### end Alembic commands ###