"""initial

Revision ID: 7506785d6350
Revises: 
Create Date: 2025-09-26 15:09:03.954132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7506785d6350'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentlogs',
    sa.Column('purchase_id', sa.String(), nullable=False, comment='ID Заказа'),
    sa.Column('telegram_id', sa.String(), nullable=False, comment='telegram id'),
    sa.Column('username', sa.String(), nullable=False, comment='telegram username'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Цена за заказ'),
    sa.Column('month_sub', sa.Integer(), nullable=False, comment='Время подписки'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание заказа'),
    sa.Column('status', sa.String(), nullable=False, comment='Статус заказа'),
    sa.Column('subscription', postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum'), nullable=False, comment='Тип подписки пользователя'),
    sa.Column('link', sa.String(), nullable=False, comment='Ссылка для оплаты заказа'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Время покупки'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False, comment='telegram id'),
    sa.Column('username', sa.String(), nullable=False, comment='telegram username'),
    sa.Column('first_name', sa.String(), nullable=True, comment='telegram first name'),
    sa.Column('last_name', sa.String(), nullable=True, comment='telegram last name'),
    sa.Column('dialogs_completed_today', sa.Integer(), nullable=True, comment='Количество завершенных диалогов сегодня'),
    sa.Column('dialogs_completed', sa.Integer(), nullable=True, comment='Количество завершенных диалогов за все время'),
    sa.Column('user_type', postgresql.ENUM('USER', 'ADMIN', 'ASSISTANT', name='user_type_enum'), nullable=False, comment='Тип пользователя'),
    sa.Column('subscription', postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum'), nullable=False, comment='Тип подписки пользователя'),
    sa.Column('subscription_date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_used', sa.Integer(), nullable=False, comment='Количество использованных сообщений в текущем периоде подписки (для STANDARD)'),
    sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True, comment='Дата начала текущей подписки'),
    sa.Column('daily_messages_used', sa.Integer(), nullable=False, comment='Daily использованные сообщения (для FREE)'),
    sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего daily reset (для FREE)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('users_dialogs_logging',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя из таблицы users'),
    sa.Column('dialogue_id', sa.UUID(), nullable=False, comment='ID сессии диалога'),
    sa.Column('role', sa.String(), nullable=False, comment='Роль отправителя (user или assistant)'),
    sa.Column('message_text', sa.String(), nullable=False, comment='Текст сообщения'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_dialogs_logging')
    op.drop_table('users')
    op.drop_table('paymentlogs')
    # ### end Alembic commands ###