"""модель логов юзера

Revision ID: ad64090b7670
Revises: e21985a6476e
Create Date: 2025-08-31 03:59:05.913578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad64090b7670'
down_revision = 'e21985a6476e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dialogs_logging', sa.Column('message', sa.String(), nullable=False, comment='Массив сообщений пользователя'))
    op.drop_column('users_dialogs_logging', 'messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dialogs_logging', sa.Column('messages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False, comment='Массив сообщений пользователя'))
    op.drop_column('users_dialogs_logging', 'message')
    # ### end Alembic commands ###
