"""change in dialog model column user_id

Revision ID: bcdb8cf481cb
Revises: 3505c6759707
Create Date: 2025-09-14 23:25:52.454573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdb8cf481cb'
down_revision = '3505c6759707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_dialogs_logging', 'user_id',
               existing_type=sa.UUID(),
               comment='ID пользователя из таблицы users',
               existing_comment='ID пользователя, совершившего запрос',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_dialogs_logging', 'user_id',
               existing_type=sa.UUID(),
               comment='ID пользователя, совершившего запрос',
               existing_comment='ID пользователя из таблицы users',
               existing_nullable=False)
    # ### end Alembic commands ###
