"""fix

Revision ID: be256bf69a43
Revises: 2beccdcf9783
Create Date: 2025-10-29 05:13:12.839163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be256bf69a43'
down_revision = '2beccdcf9783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logs', sa.Column('dialog_id', sa.UUID(), nullable=False, comment='ID диалога'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_logs', 'dialog_id')
    # ### end Alembic commands ###