"""change user and paymentlogs for subscription

Revision ID: e21985a6476e
Revises: 6feb596e8f27
Create Date: 2025-08-25 18:23:04.727982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e21985a6476e'
down_revision = '6feb596e8f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Убедитесь, что ENUM тип создан (если он новый)
    # subscription_type_enum = postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum')
    # subscription_type_enum.create(op.get_bind())

    # Для paymentlogs.subscription - уже исправлено, добавлен server_default
    op.add_column('paymentlogs',
        sa.Column('subscription',
                postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum'),
                nullable=False,
                server_default='FREE', # <-- Хорошо
                comment='Тип подписки пользователя'
        )
    )
    
    # Для users.messages_used - добавьте server_default
    op.add_column('users', 
        sa.Column('messages_used', 
                  sa.Integer(), 
                  nullable=False, 
                  server_default='0', # <-- Добавлено значение по умолчанию
                  comment='Количество использованных сообщений в текущем периоде подписки (для STANDARD)'
        )
    )
    
    # Для users.subscription_start - nullable=True, проблем быть не должно
    op.add_column('users', 
        sa.Column('subscription_start', 
                  sa.DateTime(timezone=True), 
                  nullable=True, 
                  comment='Дата начала текущей подписки'
        )
    )
    
    # Для users.daily_messages_used - добавьте server_default аналогично messages_used
    op.add_column('users', 
        sa.Column('daily_messages_used', 
                  sa.Integer(), 
                  nullable=False, 
                  server_default='0', # <-- Добавлено значение по умолчанию
                  comment='Daily использованные сообщения (для FREE)'
        )
    )
    
    # Для users.last_daily_reset - nullable=True, проблем быть не должно
    op.add_column('users', 
        sa.Column('last_daily_reset', 
                  sa.DateTime(timezone=True), 
                  nullable=True, 
                  comment='Дата последнего daily reset (для FREE)'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_reset')
    op.drop_column('users', 'daily_messages_used')
    op.drop_column('users', 'subscription_start')
    op.drop_column('users', 'messages_used')
    op.drop_column('paymentlogs', 'subscription')
    # Если вы создавали ENUM в upgrade, удалите его здесь:
    # subscription_type_enum = postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum')
    # subscription_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
