"""change in dialog model column user_id

Revision ID: bcdb8cf481cb
Revises: 3505c6759707
Create Date: 2025-09-14 23:25:52.454573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcdb8cf481cb'
down_revision = '3505c6759707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Сначала удаляем внешний ключ
    op.drop_constraint('users_dialogs_logging_user_id_fkey', 'users_dialogs_logging', type_='foreignkey')
    
    # Изменяем тип столбца user_id на UUID
    op.alter_column('users_dialogs_logging', 'user_id',
               existing_type=sa.INTEGER(),
               type_=postgresql.UUID(),
               postgresql_using='user_id::text::uuid',
               comment='ID пользователя из таблицы users',
               existing_nullable=False)
    
    # Создаем новый внешний ключ, ссылающийся на users.id
    op.create_foreign_key('users_dialogs_logging_user_id_fkey', 'users_dialogs_logging', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем внешний ключ
    op.drop_constraint('users_dialogs_logging_user_id_fkey', 'users_dialogs_logging', type_='foreignkey')
    
    # Возвращаем тип столбца user_id обратно к integer
    op.alter_column('users_dialogs_logging', 'user_id',
               existing_type=postgresql.UUID(),
               type_=sa.INTEGER(),
               postgresql_using='user_id::text::integer',
               comment='ID пользователя, совершившего запрос',
               existing_nullable=False)
    
    # Восстанавливаем внешний ключ (если нужно)
    # Обратите внимание: в downgrade мы не можем восстановить исходный внешний ключ,
    # так как он ссылался на другую таблицу/столбец
    # ### end Alembic commands ###